### ISSUE TITLE
AttributeError: 'module' object has no attribute 'site'

### ISSUE THREAD

**Issue by carchaias** [mwclient/mwclient#110]
I installed mwclient by pypi (performed upgrade to V 0.8.1) and tried with the first tutorial in [Querying-Wikipedia-with-mwclient](
https://github.com/mwclient/mwclient/wiki/Tutorial%3AQuerying-Wikipedia-with-mwclient)
Unfortunately it breaks on line 3 . Here is the output from Idle:

==== RESTART: C:\Users\xxxxx\test_mwclient.py ====

Traceback (most recent call last):
  File "C:\Users\xxxxx\test_mwclient.py", line 3, in <module>
    site = mwclient.Site('en.wikipedia.org')
AttributeError: 'module' object has no attribute 'Site'
>>>

**Comment by danmichaelo** [comment]
Hm, I don't observe that error myself. What Python version are you using?

**Comment by PierreSelim** [comment]
I cannot reproduce the bug on a windows machine. At first I though it was a windows specific problem, but it seems to work.

I've upgraded the mwclient with 

```pip install --upgrade mwclient
Collecting mwclient
  Downloading mwclient-0.8.1.tar.gz
Collecting requests (from mwclient)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |################################| 503kB 359kB/s
Collecting six (from mwclient)
  Downloading six-1.10.0-py2.py3-none-any.whl
Installing collected packages: requests, six, mwclient
  Found existing installation: requests 2.7.0
    Uninstalling requests-2.7.0:
      Successfully uninstalled requests-2.7.0
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
  Found existing installation: mwclient 0.7.2
    Uninstalling mwclient-0.7.2:
      Successfully uninstalled mwclient-0.7.2
  Running setup.py install for mwclient
Successfully installed mwclient-0.8.1 requests-2.9.1 six-1.10.0
You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.```


Then I tested the following
```Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mwclient
>>> mwclient.__ver__
'0.8.1'
>>> site = mwclient.Site('en.wikipedia.org')
>>> quit()
```

It seems to work on windows too :)

**Comment by carchaias** [comment]
My python version is 2.7.11 downloaded form [python.org](https://www.python.org/ftp/python/2.7.11/python-2.7.11.amd64.msi)

```
U:\>pip install --upgrade mwclient
Requirement already up-to-date: mwclient in c:\python27\lib\site-packages
Requirement already up-to-date: requests in c:\python27\lib\site-packages (from
mwclient)
Requirement already up-to-date: six in c:\python27\lib\site-packages (from mwcli
ent)

U:\>
```

```
import mwclient
mwclient.ver

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    mwclient.ver
AttributeError: 'module' object has no attribute 'ver'
>>> 
```

**Comment by PierreSelim** [comment]
There is no attribute `ver`, it is `__ver__` and you should be able to call it `mwclient.__ver__` after importing `mwclient`.

**Comment by carchaias** [comment]
Oops..

**Comment by danmichaelo** [comment]
Good to hear, I was a bit worried that I had introduced a bug in 0.8.1 :)
