### ISSUE TITLE
error related to .next() on GET branch

### ISSUE THREAD

**Issue by cariaso** [mwclient/mwclient#135]
I get this crash with the new GET branch

Traceback (most recent call last):
  File "./orientalbot.py", line 1386, in <module>
    main()
  File "./orientalbot.py", line 1344, in main
    oriental.tasks.flippers.do_flippers()
  File "/home/ec2-user/codetree/master/rrb/snpedia/bots/oriental/tasks/flippers.py", line 148, in do_flippers
    pagesrc=pagesrc,
  File "/home/ec2-user/codetree/master/rrb/snpedia/bots/oriental/tasks/flippers.py", line 402, in do_orientation_flip
    backs = backlinks(site, rsnum)
  File "/home/ec2-user/codetree/master/rrb/snpedia/bots/oriental/tasks/flippers.py", line 884, in backlinks
    out = set(x.name for x in site.Pages[title].backlinks()) - blacklist
  File "/home/ec2-user/codetree/master/rrb/snpedia/bots/oriental/tasks/flippers.py", line 884, in <genexpr>
    out = set(x.name for x in site.Pages[title].backlinks()) - blacklist
  File "build/bdist.linux-x86_64/egg/mwclient/listing.py", line 72, in next
  File "build/bdist.linux-x86_64/egg/mwclient/listing.py", line 165, in __next__
  File "build/bdist.linux-x86_64/egg/mwclient/listing.py", line 68, in __next__
TypeError: __next__() got an unexpected keyword argument 'full'

I don't fully understand it, but the issue seems to relate to the way that
https://github.com/mwclient/mwclient/blob/9b817ba6479b460dd6a80a19d68c7bffe226d129/mwclient/listing.py#L68
accepts full=True
but
https://github.com/mwclient/mwclient/blob/9b817ba6479b460dd6a80a19d68c7bffe226d129/mwclient/listing.py#L165
does not

**Comment by danmichaelo** [comment]
Hm, I suppose this happens on the master branch as well, probably related to the merge of #131. Failling example:

	from mwclient import Site
	site = Site('en.wikipedia.org')
	[page for page in site.allpages()]

I'll have a look at later today. Should probably add a test too.
