### ISSUE TITLE
mwclient.Site code returns a 403 error

### ISSUE THREAD

**Issue by peeter-t2** [mwclient/mwclient#137]
Hi I get the following error from the script. 

site = mwclient.Site('en.wikipedia.org')

I did update mwclient to 0.8.1, and as I understand HTTPS should be standard now as used here  https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html 

What am I doing wrong? Thanks!

```
Traceback (most recent call last):
  File "C:\Users\**\script.py", line 12, in <module>
    site = mwclient.Site('en.wikipedia.org')
  File "build\bdist.win32\egg\mwclient\client.py", line 116, in __init__
    self.site_init()
  File "build\bdist.win32\egg\mwclient\client.py", line 124, in site_init
    siprop='general|namespaces', uiprop='groups|rights', retry_on_error=False)
  File "build\bdist.win32\egg\mwclient\client.py", line 204, in api
    info = self.raw_api(action, **kwargs)
  File "build\bdist.win32\egg\mwclient\client.py", line 309, in raw_api
    res = self.raw_call('api', data, retry_on_error=retry_on_error)
  File "build\bdist.win32\egg\mwclient\client.py", line 285, in raw_call
    stream.raise_for_status()
  File "C:\Python27\lib\site-packages\requests-2.8.1-py2.7.egg\requests\models.py", line 837, in 
raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Insecure Request Forbidden - use HTTPS - https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2016-May/000110.html for url: 
http://en.wikipedia.org/w/api.php
```

**Comment by PierreSelim** [comment]
I cannot reproduce.

I have created an virutalenv and install a fresh mwclient 0.8.1:  `pip install mwclient==0.8.1`

And it works for me:
```python
>>> import mwclient
>>> mwclient.__ver__
'0.8.1'
>>> site = mwclient.Site('en.wikipedia.org')
>>> quit()
```

Can you check the result of `mwclient.__ver__` by just inserting a print or a log before the instruction that fails ?

**Comment by peeter-t2** [comment]
Thanks for the quick reaction. I made the silly error of updating the mwclient on my Python 3.5 but not on my Python 2.7 which I needed in this case. Sorry for the silly issue. Now works great! Best!
