### ISSUE TITLE
Handle session timeout on read protected wikis

### ISSUE THREAD

**Issue by danmichaelo** [mwclient/mwclient#158]
From #155 by @ubibene:

> I can login, and then immediatly get page content, save page content , etc. But : I 'm using scripts that run for a long time , scanning all wiki pages, and then  modifying page contents :  sometimes I'm getting `readapidenied` error again on my private wiki. For example when trying to save a page : 
> 
> ```
> Traceback (most recent call last):
> 
>   File "build/bdist.linux-x86_64/egg/mwclient/page.py", line 216, in save
>   File "build/bdist.linux-x86_64/egg/mwclient/page.py", line 121, in get_token
>   File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 514, in get_token
>   File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 239, in post
>   File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 282, in api
>   File "build/bdist.linux-x86_64/egg/mwclient/client.py", line 306, in handle_api_result
> mwclient.errors.APIError: (u'readapidenied', u'You need read permission to use this module', u'See http://l203psj002.mousquetaires.com/api.php for API usage')
>

*([…] The same happens when making other API calls.)*

> 
> OK, I guess the following is happening, and may happen with MW < 1.27 too : 
> - open a session with mwclient on a private wiki
> - if the session is destroyed on the server and mwclient is making an api call, mwclient calls site.get_token() (which calls action=query&meta=tokens)
> - on a private wiki this raises a readapidenied error as the only api call that can be made when unauthenticated is for getting a logintoken (action=query&meta=tokens&type=login)

**Comment by PierreSelim** [comment]
I Agree that there should probably be a maximum retry within a given period of time.

**Comment by danmichaelo** [comment]
I guess this is not strictly limited to read protected wikis, but could also be an issue with other wikis having short session timeouts?

**Comment by ubibene** [comment]
I guess so.

By the way, dealing with MW 1.27+ is a nightmare. 

My scripts which were working perfectly on a MW 1.26 are failing in many ways : 
- first the new authentication scheme (Issue #149 ) . Note that I had to use the new feature "bot password" on MW
- and now my scripts are hitting api rate limit, even if the scripts authenticates itself as a user belonging to the bot group. I ended up as putting the user used by my scripts into the sysop group, which is rate limit free

**Comment by audiodude** [comment]
I'm having a problem related to this, which I describe in https://github.com/openzim/wikimedia_wp1_bot/issues/69. Although I have attempted to catch the mwclient.errors.AssertUserFailedError and login again, that doesn't seem to be working. Any help is greatly appreciated.

**Comment by wadoli** [comment]
Just a note from a user, I ran into this problem a lot using the current [development version](https://github.com/mwclient/mwclient) today, so now I wrapped the operations in for-loops like the one below. It's not perfect but robust and it works for me™ with a read protected MediaWiki 1.39:

```python
# Save the modified page
# pattern: https://stackoverflow.com/a/7663441
for attempt in range(3):
    try:
        page.edit(str(parsed_text), edit_summary)
        logging.info(f"{page_title}: Page updated successfully.")
    except (APIError, LoginError) as e:
        site.tokens = {}  # clear token cache
        logging.info("Re-logging into the wiki...")
        site.login(wikiuser, wikipassword)
        logging.info(f"Re-logged into {odbsite} as {wikiuser}.")
    except:
        pass
    else:
        # if the process completes successfully the loop will break
        break
else:
    # we failed all the attempts - deal with the consequences.
    logging.critical(f"{page_title}: Could not update page. Skipped.")
    continue  # skip page
```
