### ISSUE TITLE
Please help : A problem in Page.delete()

### ISSUE THREAD

**Issue by The-Earth** [mwclient/mwclient#181]
I have met a problem with the delete method for page object. [Here's the code.](https://github.com/The-Earth/zhdel/blob/master/clean.py)

It prints error information like this:
```
Traceback (most recent call last):
  File "clean.py", line 44, in clean
    dpp.delete('Page kept on zhwp.')
  File "/usr/local/lib/python3.5/dist-packages/mwclient/page.py", line 293, in delete
    reason=reason, **data)
  File "/usr/local/lib/python3.5/dist-packages/mwclient/client.py", line 239, in post
    return self.api(action, 'POST', *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mwclient/client.py", line 282, in api
    if self.handle_api_result(info, sleeper=sleeper):
  File "/usr/local/lib/python3.5/dist-packages/mwclient/client.py", line 323, in handle_api_result
    info['error']['info'], info['error']['*'])
mwclient.errors.APIError: ('badtoken', 'Invalid CSRF token.', 'See https://zhdel.miraheze.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.')
```

Could anyone tell me what's the problem? Thank you!

**Comment by danmichaelo** [comment]
Is it able to delete any pages at all, or do you get this error in the middle of a long run?

Could you try something like this:

```
from mwclient.errors import APIError

[… rest of your code…]

try:
    dpp.delete('Page kept on zhwp.')
except APIError as e:
    if e.code == 'badtoken':
        print('Got badtoken, retrying')
        dp.tokens = {}   # clear token cache
        dpp.delete('Page kept on zhwp.')    # retry
```

If this helps, we could add this into mwclient. I've noticed that `Page.save()` already includes one automatic retry.

**Comment by The-Earth** [comment]
I usually got this error 24 hours after it started. I've updated the code and observing its output.

**Comment by The-Earth** [comment]
Yes it works! 👍  It once deleted a page successfully shortly after printing "Got badtoken, retrying".

**Comment by danmichaelo** [comment]
Good, thanks for testing! Did you notice if it was more or less 24 hours after the start? Not too surprisining if the tokens don't last forever, but I haven't been able to find documentation on it. In any case, it seems like token-refreshing when getting 'badtoken' is something that should be part of mwclient itself, just need to find the best place in the code to handle it (there is already a special handling in the `save` method).

**Comment by The-Earth** [comment]
It's about 18 hours this time. (Maybe shorter. I'm not quite sure about it.)
