### ISSUE TITLE
confusing error message when wiki not found

### ISSUE THREAD

**Issue by fhocutt** [mwclient/mwclient#79]
I mistakenly tried to log in to "test.wikipedia.com" instead of "test.wikipedia.org". Instead of "page not found" or similar, I got a ValueError. A more informative error message would be helpful here.

```python
>>> wiki = mwclient.Site('test.wikipedia.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fhocutt/anaconda/lib/python2.7/site-packages/mwclient/client.py", line 116, in __init__
    self.site_init()
  File "/home/fhocutt/anaconda/lib/python2.7/site-packages/mwclient/client.py", line 124, in site_init
    siprop='general|namespaces', uiprop='groups|rights')
  File "/home/fhocutt/anaconda/lib/python2.7/site-packages/mwclient/client.py", line 203, in api
    info = self.raw_api(action, **kwargs)
  File "/home/fhocutt/anaconda/lib/python2.7/site-packages/mwclient/client.py", line 295, in raw_api
    raise ValueError('Could not decode JSON: %s' % res)
ValueError
```

**Comment by danmichaelo** [comment]
Hopefully better now.
